### ISSUE TITLE
Couldn't render 1920x1080

### ISSUE THREAD

**Issue by aghzafen** [AokiAhishatsu/project_beleth#3]
Exception in thread "Thread-2" java.lang.AssertionError: A surface has changed in such a way that it is no longer compatible with the swapchain, and further presentation requests using the swapchain will fail. Applications must query the new surface properties and recreate their swapchain if they wish to continuepresenting to the surface.
	at core.util.VkUtil.vkCheckResult(VkUtil.java:62)
	at core.swapchain.SwapChain.draw(SwapChain.java:368)
	at core.engine.VkDeferredEngine.render(VkDeferredEngine.java:320)
	at core.CoreEngine.render(CoreEngine.java:114)
	at core.CoreEngine.run(CoreEngine.java:88)
	at core.CoreEngine.start(CoreEngine.java:43)
	at sandbox.SandboxWorld.main(SandboxWorld.java:25)
	at launcher.SandboxLauncher$1.lambda$0(SandboxLauncher.java:75)
	at java.lang.Thread.run(Unknown Source)

**Comment by AokiAhishatsu** [comment]
Did you just set 1920x1080 in the launcher?
I could not reproduce this.
